# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F6HPZMgZbgWZ-cecxEKBMe7W2a8a8ZSN
"""

!pip install streamlit
import streamlit as st

st.write("Hello World")

